**LAB 3**

STEP 0 - Load Library

In [3]:
pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.5.3)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.1-cp313-cp313-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.26.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Downloading scikit_learn-1.9.0-cp313-cp313-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ----- ---------------------------------- 1.0/8.2 MB 9.5 MB/s eta 0:00:01
   ------------ --------------------------- 2.6/8.2 MB 8.5 MB/s eta 0:00:01
   -------------------- ------------------- 4.2/8.2 MB 8.0 MB/s eta 0:00:01
   -------------------------- ------------- 5.5/8.2 MB 7.4 MB/s eta 0:00:01
   --------------------------------- ------ 6.8/8.2 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.2 MB 6.8 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 6.7 MB/s eta 0:00:00
Downloading joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading narwhals-2.26.0-py3-none-any.whl (474 kB)
Downloading scipy-1.18.1-cp313-cp313-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   -- ------------------------------------- 1.8/36.6 MB 8.8 MB/s eta 0:00:04
   -- ------------------------------------- 2.4/36.6 MB 8.2 MB/s eta 0:00:05
   --- ------------------------------------ 3.4/36.6 MB 5.6 MB/s eta 0:00:06
   ----- ---------------------------------- 5.0/36.6 MB 5.9 MB/s eta 0:00:06
   ------- -------------------------------- 6.8/36.6 MB 6.1 MB/s eta 0:00:05
   -------- ------------------------------- 7.9/36.6 MB 6.1 MB/s eta 0:00:05
   ---------- ----------------------------- 9.2/36.6 MB 6.0 MB/s eta 0:00:05
   ----------- ---------------------------- 10.2/36.6 MB 5.9 MB/s eta 0:00:05
   ----------- ---------------------------- 10.7/36.6 MB 5.7 MB/s eta 0:00:05
   ------------- -------------------------- 12.1/36.6 MB 5.6 MB/s eta 0:00:05
   -------------- ------------------------- 12.8/36.6 MB 5.6 MB/s eta 0:00:05
   --------------- ------------------------ 13.9/36.6 MB 5.5 MB/s eta 0:00:05
   ---------------- ----------------------- 14.9/36.6 MB 5.5 MB/s eta 0:00:04
   ----------------- ---------------------- 16.3/36.6 MB 5.5 MB/s eta 0:00:04
   ------------------ --------------------- 17.0/36.6 MB 5.4 MB/s eta 0:00:04
   ------------------- -------------------- 17.8/36.6 MB 5.3 MB/s eta 0:00:04
   -------------------- ------------------- 18.6/36.6 MB 5.2 MB/s eta 0:00:04
   --------------------- ------------------ 19.4/36.6 MB 5.1 MB/s eta 0:00:04
   ---------------------- ----------------- 20.4/36.6 MB 5.1 MB/s eta 0:00:04
   ----------------------- ---------------- 21.2/36.6 MB 5.1 MB/s eta 0:00:04
   ------------------------ --------------- 22.3/36.6 MB 5.0 MB/s eta 0:00:03
   ------------------------- -------------- 23.1/36.6 MB 5.0 MB/s eta 0:00:03
   -------------------------- ------------- 24.1/36.6 MB 5.0 MB/s eta 0:00:03
   --------------------------- ------------ 24.9/36.6 MB 4.9 MB/s eta 0:00:03
   ---------------------------- ----------- 26.0/36.6 MB 4.9 MB/s eta 0:00:03
   ----------------------------- ---------- 26.7/36.6 MB 4.9 MB/s eta 0:00:03
   ------------------------------ --------- 27.8/36.6 MB 4.9 MB/s eta 0:00:02
   ------------------------------- -------- 28.8/36.6 MB 4.9 MB/s eta 0:00:02
   -------------------------------- ------- 29.9/36.6 MB 4.9 MB/s eta 0:00:02
   --------------------------------- ------ 30.7/36.6 MB 4.9 MB/s eta 0:00:02
   ---------------------------------- ----- 31.5/36.6 MB 4.8 MB/s eta 0:00:02
   ----------------------------------- ---- 32.5/36.6 MB 4.8 MB/s eta 0:00:01
   ------------------------------------ --- 33.3/36.6 MB 4.8 MB/s eta 0:00:01
   ------------------------------------- -- 34.3/36.6 MB 4.8 MB/s eta 0:00:01
   -------------------------------------- - 35.4/36.6 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.6 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------- 36.6/36.6 MB 4.7 MB/s eta 0:00:00
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, cloudpickle, joblib, scikit-learn
Successfully installed cloudpickle-3.1.2 joblib-1.6.0 narwhals-2.26.0 scikit-learn-1.9.0 scipy-1.18.1 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

Step 1 - Load Data

In [6]:
df = pd.read_csv('Titanic-Dataset-fixed.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

**Step 2 - Slice Data**

In [7]:
df = df[['Survived', 'Pclass', 'Age', 'Sex', 'Cabin']]
df.head()

   Survived  Pclass   Age     Sex Cabin
0         0       3  22.0    male   NaN
1         1       1  38.0  female   C85
2         1       3  26.0  female   NaN
3         1       1  35.0  female  C123
4         0       3  35.0    male   NaN

**Step 3 - Encoding**

In [8]:
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])
df['Cabin'] = le.fit_transform(df['Cabin'])

Step 4 - Verify the Results

In [ ]:
df.head()

   Survived  Pclass   Age  Sex  Cabin
0         0       3  22.0    1    115
1         1       1  38.0    0     81
2         1       3  26.0    0    115
3         1       1  35.0    0     55
4         0       3  35.0    1    115

**Step 5 - Standardization**

In [9]:
std = StandardScaler()
df['Age'] = std.fit_transform(df[['Age']])

**Step 6 - Verify the Standardization Results**

In [ ]:
df.head()

   Survived  Pclass       Age  Sex  Cabin
0         0       3 -0.592481    1    115
1         1       1  0.638789    0     81
2         1       3 -0.284663    0    115
3         1       1  0.407926    0     55
4         0       3  0.407926    1    115