Lab Assignment

Assignment Description

In this practical assignment you will employ the "Wisconsin Breast Canser" dataset. The dataset comprises 569 records used for diagnosing cancer type Malignant (M) and Benign (B). Your task is to


1. Differentiate between variables that are usable and variables that are not usable.

2. Perform encoding on the "diagnosis" column.

3. Perform standardization on all columns that possess numerical values.

4. Perform the feature selection process. You may use SelectKBest.

5. Conduct the testing process using a Logistic Regression model as in practical session 1.

6. You may employ a model pipeline to facilitate your work.

7. Based on your analysis results, how many optimal features can be used? Which features are they?

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('wbc.csv')

df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.head(60)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.990,10.38,122.80,1001.0,0.11840,0.27760,0.300100,0.147100,...,17.33,184.60,2019.0,0.16220,0.66560,0.711900,0.26540,0.4601,0.11890,NaN
1,842517,M,20.570,17.77,132.90,1326.0,0.08474,0.07864,0.086900,0.070170,...,23.41,158.80,1956.0,0.12380,0.18660,0.241600,0.18600,0.2750,0.08902,NaN
2,84300903,M,19.690,21.25,130.00,1203.0,0.10960,0.15990,0.197400,0.127900,...,25.53,152.50,1709.0,0.14440,0.42450,0.450400,0.24300,0.3613,0.08758,NaN
3,84348301,M,11.420,20.38,77.58,386.1,0.14250,0.28390,0.241400,0.105200,...,26.50,98.87,567.7,0.20980,0.86630,0.686900,0.25750,0.6638,0.17300,NaN
4,84358402,M,20.290,14.34,135.10,1297.0,0.10030,0.13280,0.198000,0.104300,...,16.67,152.20,1575.0,0.13740,0.20500,0.400000,0.16250,0.2364,0.07678,NaN
5,843786,M,12.450,15.70,82.57,477.1,0.12780,0.17000,0.157800,0.080890,...,23.75,103.40,741.6,0.17910,0.52490,0.535500,0.17410,0.3985,0.12440,NaN
6,844359,M,18.250,19.98,119.60,1040.0,0.09463,0.10900,0.112700,0.074000,...,27.66,153.20,1606.0,0.14420,0.25760,0.378400,0.19320,0.3063,0.08368,NaN
7,84458202,M,13.710,20.83,90.20,577.9,0.11890,0.16450,0.093660,0.059850,...,28.14,110.60,897.0,0.16540,0.36820,0.267800,0.15560,0.3196,0.11510,NaN
8,844981,M,13.000,21.82,87.50,519.8,0.12730,0.19320,0.185900,0.093530,...,30.73,106.20,739.3,0.17030,0.54010,0.539000,0.20600,0.4378,0.10720,NaN
9,84501001,M,12.460,24.04,83.97,475.9,0.11860,0.23960,0.227300,0.085430,...,40.68,97.65,711.4,0.18530,1.05800,1.105000,0.22100,0.4366,0.20750,NaN
10,845636,M,16.020,23.24,102.70,797.8,0.08206,0.06669,0.032990,0.033230,...,33.88,123.80,1150.0,0.11810,0.15510,0.145900,0.09975,0.2948,0.08452,NaN
11,84610002,M,15.780,17.89,103.60,781.0,0.09710,0.12920,0.099540,0.066060,...,27.28,136.50,1299.0,0.13960,0.56090,0.396500,0.18100,0.3792,0.10480,NaN
12,846226,M,19.170,24.80,132.40,1123.0,0.09740,0.24580,0.206500,0.111800,...,29.94,151.70,1332.0,0.10370,0.39030,0.363900,0.17670,0.3176,0.10230,NaN
13,846381,M,15.850,23.95,103.70,782.7,0.08401,0.10020,0.099380,0.053640,...,27.66,112.00,876.5,0.11310,0.19240,0.232200,0.11190,0.2809,0.06287,NaN
14,84667401,M,13.730,22.61,93.60,578.3,0.11310,0.22930,0.212800,0.080250,...,32.01,108.80,697.7,0.16510,0.77250,0.694300,0.22080,0.3596,0.14310,NaN
15,84799002,M,14.540,27.54,96.73,658.8,0.11390,0.15950,0.163900,0.073640,...,37.13,124.10,943.2,0.16780,0.65770,0.702600,0.17120,0.4218,0.13410,NaN
16,848406,M,14.680,20.13,94.74,684.5,0.09867,0.07200,0.073950,0.052590,...,30.88,123.40,1138.0,0.14640,0.18710,0.291400,0.16090,0.3029,0.08216,NaN
17,84862001,M,16.130,20.68,108.10,798.8,0.11700,0.20220,0.172200,0.102800,...,31.48,136.80,1315.0,0.17890,0.42330,0.478400,0.20730,0.3706,0.11420,NaN
18,849014,M,19.810,22.15,130.00,1260.0,0.09831,0.10270,0.147900,0.094980,...,30.88,186.80,2398.0,0.15120,0.31500,0.537200,0.23880,0.2768,0.07615,NaN
19,8510426,B,13.540,14.36,87.46,566.3,0.09779,0.08129,0.066640,0.047810,...,19.26,99.70,711.2,0.14400,0.17730,0.239000,0.12880,0.2977,0.07259,NaN
20,8510653,B,13.080,15.71,85.63,520.0,0.10750,0.12700,0.045680,0.031100,...,20.49,96.09,630.5,0.13120,0.27760,0.189000,0.07283,0.3184,0.08183,NaN
21,8510824,B,9.504,12.44,60.34,273.9,0.10240,0.06492,0.029560,0.020760,...,15.66,65.13,314.9,0.13240,0.11480,0.088670,0.06227,0.2450,0.07773,NaN
22,8511133,M,15.340,14.26,102.50,704.4,0.10730,0.21350,0.207700,0.097560,...,19.08,125.10,980.9,0.13900,0.59540,0.630500,0.23930,0.4667,0.09946,NaN
23,851509,M,21.160,23.04,137.20,1404.0,0.09428,0.10220,0.109700,0.086320,...,35.59,188.00,2615.0,0.14010,0.26000,0.315500,0.20090,0.2822,0.07526,NaN
24,852552,M,16.650,21.38,110.00,904.6,0.11210,0.14570,0.152500,0.091700,...,31.56,177.00,2215.0,0.18050,0.35780,0.469500,0.20950,0.3613,0.09564,NaN
25,852631,M,17.140,16.40,116.00,912.7,0.11860,0.22760,0.222900,0.140100,...,21.40,152.40,1461.0,0.15450,0.39490,0.385300,0.25500,0.4066,0.10590,NaN
26,852763,M,14.580,21.53,97.41,644.8,0.10540,0.18680,0.142500,0.087830,...,33.21,122.40,896.9,0.15250,0.66430,0.553900,0.27010,0.4264,0.12750,NaN
27,852781,M,18.610,20.25,122.10,1094.0,0.09440,0.10660,0.149000,0.077310,...,27.26,139.90,1403.0,0.13380,0.21170,0.344600,0.14900,0.2341,0.07421,NaN
28,852973,M,15.300,25.27,102.40,732.4,0.10820,0.16970,0.168300,0.087510,...,36.71,149.30,1269.0,0.16410,0.61100,0.633500,0.20240,0.4027,0.09876,NaN
29,853201,M,17.570,15.05,115.00,955.1,0.09847,0.11570,0.098750,0.079530,...,19.52,134.90,1227.0,0.12550,0.28120,0.248900,0.14560,0.2756,0.07919,NaN
30,853401,M,18.630,25.11,124.80,1088.0,0.10640,0.18870,0.231900,0.124400,...,34.01,160.50,1670.0,0.14910,0.42570,0.613300,0.18480,0.3444,0.09782,NaN
31,853612,M,11.840,18.70,77.93,440.6,0.11090,0.15160,0.121800,0.051820,...,28.12,119.40,888.7,0.16370,0.57750,0.695600,0.15460,0.4761,0.14020,NaN
32,85382601,M,17.020,23.98,112.80,899.3,0.11970,0.14960,0.241700,0.120300,...,32.09,136.10,1344.0,0.16340,0.35590,0.558800,0.18470,0.3530,0.08482,NaN
33,854002,M,19.270,26.47,127.90,1162.0,0.09401,0.17190,0.165700,0.075930,...,30.90,161.40,1813.0,0.15090,0.65900,0.609100,0.17850,0.3672,0.11230,NaN
34,854039,M,16.130,17.88,107.00,807.2,0.10400,0.15590,0.135400,0.077520,...,27.26,132.70,1261.0,0.14460,0.58040,0.527400,0.18640,0.4270,0.12330,NaN
35,854253,M,16.740,21.59,110.10,869.5,0.09610,0.13360,0.134800,0.060180,...,29.02,133.50,1229.0,0.15630,0.38350,0.540900,0.18130,0.4863,0.08633,NaN
36,854268,M,14.250,21.72,93.63,633.0,0.09823,0.10980,0.131900,0.055980,...,30.36,116.20,799.6,0.14460,0.42380,0.518600,0.14470,0.3591,0.10140,NaN
37,854941,B,13.030,18.42,82.61,523.8,0.08983,0.03766,0.025620,0.029230,...,22.81,84.46,545.9,0.09701,0.04619,0.048330,0.05013,0.1987,0.06169,NaN
38,855133,M,14.990,25.20,95.54,698.8,0.09387,0.05131,0.023980,0.028990,...,25.20,95.54,698.8,0.09387,0.05131,0.023980,0.02899,0.1565,0.05504,NaN
39,855138,M,13.480,20.82,88.40,559.2,0.10160,0.12550,0.106300,0.054390,...,26.02,107.30,740.4,0.16100,0.42250,0.503000,0.22580,0.2807,0.10710,NaN
40,855167,M,13.440,21.58,86.18,563.0,0.08162,0.06031,0.031100,0.020310,...,30.25,102.50,787.9,0.10940,0.20430,0.208500,0.11120,0.2994,0.07146,NaN
41,855563,M,10.950,21.35,71.90,371.1,0.12270,0.12180,0.104400,0.056690,...,35.34,87.22,514.0,0.19090,0.26980,0.402300,0.14240,0.2964,0.09606,NaN
42,855625,M,19.070,24.81,128.30,1104.0,0.09081,0.21900,0.210700,0.099610,...,33.17,177.40,1651.0,0.12470,0.74440,0.724200,0.24930,0.4670,0.10380,NaN
43,856106,M,13.280,20.28,87.32,545.2,0.10410,0.14360,0.098470,0.061580,...,28.00,113.10,907.2,0.15300,0.37240,0.366400,0.14920,0.3739,0.10270,NaN
44,85638502,M,13.170,21.81,85.42,531.5,0.09714,0.10470,0.082590,0.052520,...,29.89,105.50,740.7,0.15030,0.39040,0.372800,0.16070,0.3693,0.09618,NaN
45,857010,M,18.650,17.60,123.70,1076.0,0.10990,0.16860,0.197400,0.100900,...,21.32,150.60,1567.0,0.16790,0.50900,0.734500,0.23780,0.3799,0.09185,NaN
46,85713702,B,8.196,16.84,51.71,201.9,0.08600,0.05943,0.015880,0.005917,...,21.96,57.26,242.2,0.12970,0.13570,0.068800,0.02564,0.3105,0.07409,NaN
47,85715,M,13.170,18.66,85.98,534.6,0.11580,0.12310,0.122600,0.073400,...,27.95,102.80,759.4,0.17860,0.41660,0.500600,0.20880,0.3900,0.11790,NaN
48,857155,B,12.050,14.63,78.04,449.3,0.10310,0.09092,0.065920,0.027490,...,20.70,89.88,582.6,0.14940,0.21560,0.305000,0.06548,0.2747,0.08301,NaN
49,857156,B,13.490,22.30,86.91,561.0,0.08752,0.07698,0.047510,0.033840,...,31.82,99.00,698.8,0.11620,0.17110,0.228200,0.12820,0.2871,0.06917,NaN
50,857343,B,11.760,21.60,74.72,427.9,0.08637,0.04966,0.016570,0.011150,...,25.72,82.98,516.5,0.10850,0.08615,0.055230,0.03715,0.2433,0.06563,NaN
51,857373,B,13.640,16.34,87.21,571.8,0.07685,0.06059,0.018570,0.017230,...,23.19,96.08,656.7,0.10890,0.15820,0.105000,0.08586,0.2346,0.08025,NaN
52,857374,B,11.940,18.24,75.71,437.6,0.08261,0.04751,0.019720,0.013490,...,21.33,83.67,527.2,0.11440,0.08906,0.092030,0.06296,0.2785,0.07408,NaN
53,857392,M,18.220,18.70,120.30,1033.0,0.11480,0.14850,0.177200,0.106000,...,24.13,135.10,1321.0,0.12800,0.22970,0.262300,0.13250,0.3021,0.07987,NaN
54,857438,M,15.100,22.02,97.26,712.8,0.09056,0.07081,0.052530,0.033340,...,31.69,117.70,1030.0,0.13890,0.20570,0.271200,0.15300,0.2675,0.07873,NaN
55,85759902,B,11.520,18.75,73.34,409.0,0.09524,0.05473,0.030360,0.022780,...,22.47,81.81,506.2,0.12490,0.08720,0.090760,0.06316,0.3306,0.07036,NaN
56,857637,M,19.210,18.57,125.50,1152.0,0.10530,0.12670,0.132300,0.089940,...,28.14,170.10,2145.0,0.16240,0.35110,0.387900,0.20910,0.3537,0.08294,NaN
57,857793,M,14.710,21.59,95.55,656.9,0.11370,0.13650,0.129300,0.081230,...,30.70,115.70,985.5,0.13680,0.42900,0.358700,0.18340,0.3698,0.10940,NaN
58,857810,B,13.050,19.31,82.61,527.2,0.08060,0.03789,0.000692,0.004167,...,22.25,90.24,624.1,0.10210,0.06191,0.001845,0.01111,0.2439,0.06289,NaN
59,858477,B,8.618,11.79,54.34,224.5,0.09752,0.05272,0.020610,0.007799,...,15.40,59.90,274.9,0.17330,0.12390,0.116800,0.04419,0.3220,0.09026,NaN

# ANSWER 1  (Differentiate between variables that are usable and variables that are not usable.)

*Usable Variable :*
- perimeter_mean
- concavity_mean
- radius_se
- perimeter_se
- symmetry_worst
- compactness_worst
- perimeter_worst

*Not Usable Variable :*
- radius_mean
- texture_mean	
- area_mean
- smoothness_mean	
- compactness_mean	 
- concave points_mean	
- symmetry_mean	
- fractal_dimension_mean		
- texture_se	
- area_se	
- smoothness_se	
- compactness_se	
- concavity_se	
- concave points_se	
- symmetry_se	
- fractal_dimension_se	
- radius_worst	
- texture_worst		
- area_worst	
- smoothness_worst	
- concavity_worst	
- concave points_worst	
- fractal_dimension_worst	
- Unnamed: 32

In [4]:
df = df[['diagnosis', 'perimeter_mean', 'concavity_mean', 'radius_se', 'perimeter_se', 'symmetry_worst', 'compactness_worst', 'perimeter_worst' ]]
df.head()

,diagnosis,perimeter_mean,concavity_mean,radius_se,perimeter_se,symmetry_worst,compactness_worst,perimeter_worst
0,M,122.80,0.3001,1.0950,8.589,0.4601,0.6656,184.60
1,M,132.90,0.0869,0.5435,3.398,0.2750,0.1866,158.80
2,M,130.00,0.1974,0.7456,4.585,0.3613,0.4245,152.50
3,M,77.58,0.2414,0.4956,3.445,0.6638,0.8663,98.87
4,M,135.10,0.1980,0.7572,5.438,0.2364,0.2050,152.20

# ANSWER 2 (Perform encoding on the "diagnosis" column)

In [5]:
le = LabelEncoder()
df['diagnosis'] = le.fit_transform(df['diagnosis'])

In [6]:
df.head()

,diagnosis,perimeter_mean,concavity_mean,radius_se,perimeter_se,symmetry_worst,compactness_worst,perimeter_worst
0,1,122.80,0.3001,1.0950,8.589,0.4601,0.6656,184.60
1,1,132.90,0.0869,0.5435,3.398,0.2750,0.1866,158.80
2,1,130.00,0.1974,0.7456,4.585,0.3613,0.4245,152.50
3,1,77.58,0.2414,0.4956,3.445,0.6638,0.8663,98.87
4,1,135.10,0.1980,0.7572,5.438,0.2364,0.2050,152.20

# ANSWER 3 (Perform standardization on all columns that possess numerical values)

In [7]:
std = StandardScaler()

num_cols = df.select_dtypes(include=['number']).columns
df[num_cols] = std.fit_transform(df[num_cols])
df.head()

,diagnosis,perimeter_mean,concavity_mean,radius_se,perimeter_se,symmetry_worst,compactness_worst,perimeter_worst
0,1.297676,1.269934,2.652874,2.489734,2.833031,2.750622,2.616665,2.303601
1,1.297676,1.685955,-0.023846,0.499255,0.263327,-0.243890,-0.430444,1.535126
2,1.297676,1.566503,1.363478,1.228676,0.850928,1.152255,1.082932,1.347475
3,1.297676,-0.592687,1.915897,0.326373,0.286593,6.046041,3.893397,-0.249939
4,1.297676,1.776573,1.371011,1.270543,1.273189,-0.868353,-0.313395,1.338539

# ANSWER 4 (Perform the feature selection process. You may use SelectKBest.)